drop table IF EXISTS users;
create table users (
   id serial primary key,
   name varchar(255) not null,
   passphrase varchar(255) not null,
   auth_token varchar(255) not null
);
drop table IF EXISTS cloudfiles;
CREATE TABLE cloudfiles (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"size" int4 NOT NULL,
	auth_token varchar(255) NULL,
	filename varchar(255) NULL,
	filepath varchar(255) NULL,
	last_change varchar(255) NULL,
	CONSTRAINT cloudfiles_pkey PRIMARY KEY (id)
);